# Development override for docker-compose
# Use: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  app:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port

  database:
    ports:
      - "3306:3306" # Expose database port for local access 